# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
remote_theme: "Phlow/feeling-responsive@1.91"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
livereload: true
github: [metadata]

# Title of your website
title: 'queereducation.github.io'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'queereducation.github.io'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: >-
  queereducation.github.io

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Created with &hearts; by <a href="/authors">Klaus Gittelman</a> and <a href="/authors">Freya Glick</a> with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

# Main author of the website
# See > authors.yml
author: klaus

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://queereducation.github.io'
baseurl: ''

# Logo size is 600x80 pixels
# logo: "logo.png"
header: no

#       ____              _             __  _
#      / __ \____ _____ _(_)___  ____ _/ /_(_)___  ____
#     / /_/ / __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
#    / ____/ /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
#   /_/    \__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
#               /____/
#
#paginate: 5                      # Paginates all X entries
#paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work

# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
  - temp.txt
  - readme.md
  - '*.code-workspace'
  - Gemfile
  - Gemfile.lock

#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: ''
    values:
      header: no
      comments: false
      show_meta: false
      author: klaus

#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
  style    : compressed