# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
remote_theme: "Phlow/feeling-responsive@1.91"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
livereload: true
github: [metadata]

# Search Engine Information
title: queereducation.github.io
description: >- # this means to ignore newlines until "next tag:"
  queereducation.github.io
baseurl:
url: https://queereducation.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Disable the feed in the footer
atom_feed:
  hide: true

# Header
masthead_title: "queereducation.github.io"

# Footer
name: a
email: a

# Site Author
author:
  name             : "Klaus Gittelman"
  avatar           : "/assets/images/bio/bio.jpg"
  bio              : 
  email            : "rg1024400@wcupa.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:a"

# Exclude from processing.
# The following items will not be processed, by default.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - temp.txt
  - readme.md
  - '*.code-workspace'
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
  - Gemfile
  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      permalink: /blog/:year/:month/:day/:title/
      toc: true
      toc_sticky: true
      show_tags: true
  - scope:
      path: "_drafts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      permalink: /blog/:year/:month/:day/:title/
      toc: true
      toc_sticky: true
      show_tags: true
